server:
  port: 8090

logging:
  level:
    org.example: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: KirMih9087
  jpa:
    hibernate:
      ddl-auto: update